name: pytest
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10.0-alpha.6']
    name: Test on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install packages
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov requests
      - name: Describe python environment
        env:
          DETA_PROJECT_KEY=${{ secrets.DETA_PROJECT_KEY  }}
        run: |
          python3 --version
          which python3
          pip list
      - name: Run pytest
        run: pytest
